/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORTS_H_RPCGEN
#define _AIRPORTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *stringtype;

typedef struct airportnode *airportlist;

struct airportnode {
	stringtype code;
	stringtype name;
	float latitude;
	float longitude;
	float distance;
	airportlist next;
};
typedef struct airportnode airportnode;

struct airportdata {
	float latitude;
	float longitude;
};
typedef struct airportdata airportdata;

struct airport_ret {
	int err;
	union {
		airportlist list;
	} airport_ret_u;
};
typedef struct airport_ret airport_ret;

#define AIRPORTPROG 0x38886665
#define AIRPORT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define AIRPORTS 1
extern  airport_ret * airports_1(airportdata *, CLIENT *);
extern  airport_ret * airports_1_svc(airportdata *, struct svc_req *);
extern int airportprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AIRPORTS 1
extern  airport_ret * airports_1();
extern  airport_ret * airports_1_svc();
extern int airportprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_stringtype (XDR *, stringtype*);
extern  bool_t xdr_airportlist (XDR *, airportlist*);
extern  bool_t xdr_airportnode (XDR *, airportnode*);
extern  bool_t xdr_airportdata (XDR *, airportdata*);
extern  bool_t xdr_airport_ret (XDR *, airport_ret*);

#else /* K&R C */
extern bool_t xdr_stringtype ();
extern bool_t xdr_airportlist ();
extern bool_t xdr_airportnode ();
extern bool_t xdr_airportdata ();
extern bool_t xdr_airport_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORTS_H_RPCGEN */
