/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *nametype;

typedef char *statetype;

typedef struct placenode *placelist;

struct placenode {
	nametype placename;
    statetype state;
    //nametype code;
    //float distance;
    float latitude;
    float longitude;
	placelist next;
};
typedef struct placenode placenode;

struct placedata {
	nametype name;
	statetype state;
};
typedef struct placedata placedata;

struct places_ret {
	int err;
	union {
		placelist list;
	} places_ret_u;
};
typedef struct places_ret places_ret;

#define PLACESPROG 0x202A6358
#define PLACES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PLACES 1
extern  places_ret * places_1(placedata *, CLIENT *);
extern  places_ret * places_1_svc(placedata *, struct svc_req *);
extern int placesprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PLACES 1
extern  places_ret * places_1();
extern  places_ret * places_1_svc();
extern int placesprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);
extern  bool_t xdr_statetype (XDR *, statetype*);
extern  bool_t xdr_placelist (XDR *, placelist*);
extern  bool_t xdr_placenode (XDR *, placenode*);
extern  bool_t xdr_placedata (XDR *, placedata*);
extern  bool_t xdr_places_ret (XDR *, places_ret*);

#else /* K&R C */
extern bool_t xdr_nametype ();
extern bool_t xdr_statetype ();
extern bool_t xdr_placelist ();
extern bool_t xdr_placenode ();
extern bool_t xdr_placedata ();
extern bool_t xdr_places_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
