/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"
#include "airports.h"

void
airportprog_1(char *host)
{
  CLIENT *clnt;
  airport_ret  *result_1;
  airportdata  airports_1_arg;

  airports_1_arg.latitude = 47.61;
  airports_1_arg.longitude = -117.3013;
  
  printf("in places server\n");
		
#ifndef DEBUG
  clnt = clnt_create (host, AIRPORTPROG, AIRPORT_VERS, "udp");
  if (clnt == NULL) {
	printf("no client");
	clnt_pcreateerror (host);
	exit (1);
  }
#endif  /* DEBUG */
  
  result_1 = airports_1(&airports_1_arg, clnt);
  if (result_1 == (airport_ret *) NULL) {
	clnt_perror (clnt, "call failed");
  } else {
	printf("call successful\n");
	airportlist list;
	list = result_1 -> airport_ret_u.list;
	while (list != NULL) {
	  printf ("%s %s %f %f dist: %f \n", list -> code, list ->name, list -> latitude, list -> longitude, list->distance);
	  list = list -> next;
	}
  }
#ifndef DEBUG
  clnt_destroy (clnt);
#endif   /* DEBUG */
}

places_ret *
places_1_svc(placedata *argp, struct svc_req *rqstp)
{
  placedata *p = argp;
  char *city = p -> name;
  char *state = p -> state;
  printf("places server received: %s, %s\n", city, state);
  static places_ret  result;
  char *host = "localhost";
  /*
   * insert server code here
   */
  airportprog_1(host);
  
  printf("really in places server\n");
  return &result;
}
